### ISSUE TITLE
При размере amount больше initialBalance, но меньше creditLimit итоговый баланс меньше creditLimit в методе pay в классе CreditAccount

### ISSUE THREAD

**Issue by Kvazavr** [Kvazavr/javaqa-team-diplom-2#14]
# Описание
При размере amount больше initialBalance, но меньше creditLimit итоговый баланс меньше creditLimit в методе pay в классе CreditAccount

# Локация дефекта
https://github.com/Kvazavr/javaqa-team-diplom-2/blob/63dcd78cf7327fbd28193e4ca633769a8d724090/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L43

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/netology-code/javaqa-team-diplom-2) в IDEA
2. Создать объект класса *CreditAccount* с начальным балансом 5_000, с кредитным лимитом  5_000, ставка 15
3. В методе *pay* размер *amount* установить 6_000.
4. Вызвать метод *pay*

*Ожидаемый результат:* Баланс равен -1_000
*Фактический результат:* Баланс равен -6_000

# Скриншот
![Dont calculate balance javaqa-team-diplom-2 – CreditAccount java 2023-04-](https://user-images.githubusercontent.com/122520677/230320110-8223ee6e-600d-4656-8977-eeec9e79ae9d.png)

# Тест
https://github.com/Kvazavr/javaqa-team-diplom-2/blob/b96cd1c5f65db657980c62aa59d06ba89d7bc3a2/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L70-L82

# Окружение
*  **Операционная система:** Windows 10 Pro версия 21Н2
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** 11 Eclipse Temurin Version 11.0.17

**Comment by ivashatunova** [comment]
Fixed with https://github.com/Kvazavr/javaqa-team-diplom-2/commit/380827d054f7ca1b0a4ac81265f23e6187a5336d
