### ISSUE TITLE
При расчете годовой ставки округление приводит к неверному расчету итоговой ставки в методе yearCharge в классе CreditAccount  

### ISSUE THREAD

**Issue by Kvazavr** [Kvazavr/javaqa-team-diplom-2#17]
# Описание
В методе yearChange в классе CreditAccount при расчете годовой ставки округление происходит на промежуточном этапе, что приводит к неверному расчету итоговой ставки

# Локация дефекта
https://github.com/Kvazavr/javaqa-team-diplom-2/blob/63dcd78cf7327fbd28193e4ca633769a8d724090/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L87-L90

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/netology-code/javaqa-team-diplom-2) в IDEA
2. Создать объект класса *CreditAccount* с начальным балансом -242, с кредитным лимитом  5_000, ставка 15
3. Вызвать метод yearChange

*Ожидаемый результат:* -36
*Фактический результат:* -30

# Скриншот
![Rate javaqa-team-diplom-2 – CreditAccount java 2023-04-](https://user-images.githubusercontent.com/122520677/230332035-db46d5e6-227e-4668-8580-7113505004a5.png)

# Тест
https://github.com/Kvazavr/javaqa-team-diplom-2/blob/9acf05f359aa228c66486204814c9e84146c1c77/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L146-L156

# Окружение
*  **Операционная система:** Windows 10 Pro версия 21Н2
* **IDE:** IntelliJ IDEA Community Edition 2022.3.2
* **JAVA:** 11 Eclipse Temurin Version 11.0.17

**Comment by ivashatunova** [comment]
fixed by https://github.com/Kvazavr/javaqa-team-diplom-2/commit/2026124dbd4a1409bacc9f40de0bb1e3370d44d6
